spring:
  application:
    name: projet
  datasource:
    url: jdbc:mysql://localhost:3306/projetWeb
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration